# language: node_js

# node_js: 8

# before_script:
# - npm install -g firebase-tools

# script:
#   - firebase deploy --project pray-for-sound --token $FIREBASE_TOKEN

# language: node_js
# node_js:
#   - "node"
# script:
#   - cd functions
#   - npm install
#   - cd ..
# deploy:
#   provider: firebase
#   token:
#     secure: "$FIREBASE_TOKEN"
#   skip_cleanup: true

  deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN"